package br.com.brunoszczuk.apontahidrometro.domain;
// Generated 31/07/2018 18:08:45 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name = "permissao",
         schema = "public"
)
public class Permissao implements java.io.Serializable {

    private int cdPermissao;
    private String nmRotina;

    public Permissao() {
    }

    public Permissao(int cdPermissao) {
        this.cdPermissao = cdPermissao;
    }

    public Permissao(int cdPermissao, String nmRotina) {
        this.cdPermissao = cdPermissao;
        this.nmRotina = nmRotina;
    }

    @Id

    @Column(name = "cd_permissao", unique = true, nullable = false)
    public int getCdPermissao() {
        return this.cdPermissao;
    }

    public void setCdPermissao(int cdPermissao) {
        this.cdPermissao = cdPermissao;
    }

    @Column(name = "nm_rotina", length = 60)
    public String getNmRotina() {
        return this.nmRotina;
    }

    public void setNmRotina(String nmRotina) {
        this.nmRotina = nmRotina;
    }

    @Override
    public String toString() {
        return "Permissao{" + "cdPermissao=" + cdPermissao + ", nmRotina=" + nmRotina  + '}';
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 41 * hash + this.cdPermissao;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Permissao other = (Permissao) obj;
        if (this.cdPermissao != other.cdPermissao) {
            return false;
        }
        return true;
    }
    

}
