package br.com.brunoszczuk.apontahidrometro.domain;
// Generated 31/07/2018 18:08:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permissaotipousuario generated by hbm2java
 */
@Entity
@Table(name="permissaotipousuario"
    ,schema="public"
)
public class Permissaotipousuario  implements java.io.Serializable {


     private PermissaotipousuarioId id;
     private Permissao permissao;
     private TipoUsuario tipousuario;
     private Date dtInclusao;
     private Date dtUltimaatualizacao;

    public Permissaotipousuario() {
    }

	
    public Permissaotipousuario(PermissaotipousuarioId id, Permissao permissao, TipoUsuario tipousuario) {
        this.id = id;
        this.permissao = permissao;
        this.tipousuario = tipousuario;
    }
    public Permissaotipousuario(PermissaotipousuarioId id, Permissao permissao, TipoUsuario tipousuario, Date dtInclusao, Date dtUltimaatualizacao) {
       this.id = id;
       this.permissao = permissao;
       this.tipousuario = tipousuario;
       this.dtInclusao = dtInclusao;
       this.dtUltimaatualizacao = dtUltimaatualizacao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cdTipoUsuario", column=@Column(name="cd_tipousuario", nullable=false, length=30) ), 
        @AttributeOverride(name="cdPermissao", column=@Column(name="cd_permissao", nullable=false) ) } )
    public PermissaotipousuarioId getId() {
        return this.id;
    }
    
    public void setId(PermissaotipousuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_permissao", nullable=false, insertable=false, updatable=false)
    public Permissao getPermissao() {
        return this.permissao;
    }
    
    public void setPermissao(Permissao permissao) {
        this.permissao = permissao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_tipousuario", nullable=false, insertable=false, updatable=false)
    public TipoUsuario getTipoUsuario() {
        return this.tipousuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipousuario) {
        this.tipousuario = tipousuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_inclusao", length=35)
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="dt_ultimaatualizacao", length=21)
    public Date getDtUltimaatualizacao() {
        return this.dtUltimaatualizacao;
    }
    
    public void setDtUltimaatualizacao(Date dtUltimaatualizacao) {
        this.dtUltimaatualizacao = dtUltimaatualizacao;
    }

    @Override
    public String toString() {
        return "Permissaotipousuario{" + "id=" + id + ", permissao=" + permissao + ", tipousuario=" + tipousuario + ", dtInclusao=" + dtInclusao + ", dtUltimaatualizacao=" + dtUltimaatualizacao + '}';
    }

 



}


