package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.validator.constraints.EAN;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente",
        schema = "public"
)
public class Cliente implements java.io.Serializable {

    private int cdCliente;
    @NotNull(message = "{message.cliente.endereco}")
    private Endereco endereco;
    @NotNull(message = "{message.cliente.formapagto}")
    private Formapagto formapagto;
    @NotBlank(message = "{message.cliente.nrloja}")
    @Size(min = 4, max=4)
    private String nrLoja;
    @NotBlank(message = "{message.cliente.tpcliente}")
    @Size(max = 2)
    private String tpCliente;
    @NotBlank(message = "{message.cliente.nrcnpjcpf}")
    @Size(max = 14)
    private String nrCnpjcpf;
    @NotBlank(message = "{message.cliente.nmcliente}")
    @Size(max = 120)
    private String nmCliente;
    @NotBlank(message = "{message.cliente.nmfantasia}")
    @Size(max = 120)
    private String nmFantasia;
    
    private String nrDdd;
    
    private String nrTelefone;
    @NotBlank(message = "{message.cliente.dsemail}")
    @Email
    @Size(max = 100)
    private String dsEmail;
    private String stStatus;
    private Set<Unidadeconsumidora> unidadeconsumidoras = new HashSet<>(0);
    private Set<Contrato> contratos = new HashSet<>(0);
    private Set<Contareceber> contarecebers = new HashSet<>(0);

    public Cliente() {
    }

    public Cliente(int cdCliente, Endereco endereco, String nrLoja, String tpCliente, String nrCnpjcpf, String nmCliente, String nmFantasia, String dsEmail, String stStatus, Formapagto formapagto) {
        this.cdCliente = cdCliente;
        this.endereco = endereco;
        this.nrLoja = nrLoja;
        this.tpCliente = tpCliente;
        this.nrCnpjcpf = nrCnpjcpf;
        this.nmCliente = nmCliente;
        this.nmFantasia = nmFantasia;
        this.dsEmail = dsEmail;
        this.stStatus = stStatus;
        this.formapagto = formapagto;
    }

    public Cliente(int cdCliente, Endereco endereco, String nrLoja, String tpCliente, String nrCnpjcpf, String nmCliente, String nmFantasia, String nrDdd, String nrTelefone, String dsEmail, String stStatus, Set<Unidadeconsumidora> unidadeconsumidoras, Set<Contrato> contratos, Set<Contareceber> contarecebers) {
        this.cdCliente = cdCliente;
        this.endereco = endereco;
        this.nrLoja = nrLoja;
        this.tpCliente = tpCliente;
        this.nrCnpjcpf = nrCnpjcpf;
        this.nmCliente = nmCliente;
        this.nmFantasia = nmFantasia;
        this.nrDdd = nrDdd;
        this.nrTelefone = nrTelefone;
        this.dsEmail = dsEmail;
        this.stStatus = stStatus;
        this.unidadeconsumidoras = unidadeconsumidoras;
        this.contratos = contratos;
        this.contarecebers = contarecebers;
    }

    @Id

    @Column(name = "cd_cliente", nullable = false)
    public int getCdCliente() {
        return this.cdCliente;
    }

    public void setCdCliente(int cdCliente) {
        this.cdCliente = cdCliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @Fetch(FetchMode.JOIN)
    @JoinColumn(name = "cd_formapagto", nullable = false)
    public Formapagto getFormapagto() {
        return formapagto;
    }

    public void setFormapagto(Formapagto formapagto) {
        this.formapagto = formapagto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @Fetch(FetchMode.JOIN)
    @JoinColumn(name = "cd_endereco", nullable = false)
    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    @Column(name = "nr_loja", nullable = false, length = 4)
    public String getNrLoja() {
        return this.nrLoja;
    }

    public void setNrLoja(String nrLoja) {
        this.nrLoja = nrLoja;
    }

    @Column(name = "tp_cliente", nullable = false, length = 2)
    public String getTpCliente() {
        return this.tpCliente;
    }

    public void setTpCliente(String tpCliente) {
        this.tpCliente = tpCliente;
    }

    @Column(name = "nr_cnpjcpf", nullable = false, length = 14)
    public String getNrCnpjcpf() {
        return this.nrCnpjcpf;
    }

    public void setNrCnpjcpf(String nrCnpjcpf) {
        this.nrCnpjcpf = nrCnpjcpf;
    }

    @Column(name = "nm_cliente", nullable = false, length = 120)
    public String getNmCliente() {
        return this.nmCliente;
    }

    public void setNmCliente(String nmCliente) {
        this.nmCliente = nmCliente;
    }

    @Column(name = "nm_fantasia", nullable = false, length = 120)
    public String getNmFantasia() {
        return this.nmFantasia;
    }

    public void setNmFantasia(String nmFantasia) {
        this.nmFantasia = nmFantasia;
    }

    @Column(name = "nr_ddd", length = 3)
    public String getNrDdd() {
        return this.nrDdd;
    }

    public void setNrDdd(String nrDdd) {
        this.nrDdd = nrDdd;
    }

    @Column(name = "nr_telefone", length = 40)
    public String getNrTelefone() {
        return this.nrTelefone;
    }

    public void setNrTelefone(String nrTelefone) {
        this.nrTelefone = nrTelefone;
    }

    @Column(name = "ds_email", nullable = false, length = 100)
    public String getDsEmail() {
        return this.dsEmail;
    }

    public void setDsEmail(String dsEmail) {
        this.dsEmail = dsEmail;
    }

    @Column(name = "st_status", nullable = false, length = 20)
    public String getStStatus() {
        return this.stStatus;
    }

    public void setStStatus(String stStatus) {
        this.stStatus = stStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public Set<Unidadeconsumidora> getUnidadeconsumidoras() {
        return this.unidadeconsumidoras;
    }

    public void setUnidadeconsumidoras(Set<Unidadeconsumidora> unidadeconsumidoras) {
        this.unidadeconsumidoras = unidadeconsumidoras;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public Set<Contrato> getContratos() {
        return this.contratos;
    }

    public void setContratos(Set<Contrato> contratos) {
        this.contratos = contratos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public Set<Contareceber> getContarecebers() {
        return this.contarecebers;
    }

    public void setContarecebers(Set<Contareceber> contarecebers) {
        this.contarecebers = contarecebers;
    }

}
