package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contareceber generated by hbm2java
 */
@Entity
@Table(name="contareceber"
    ,schema="public"
)
public class Contareceber  implements java.io.Serializable {


     private int cdConta;
     private Cliente cliente;
     private Formapagto formapagto;
     private String nrTitulo;
     private boolean stAtivo;
     private BigDecimal vlDesconto;
     private Date dtEmissao;
     private boolean stBaixado;
     private BigDecimal vlTitulo;
     private BigDecimal vlAcrescimo;
     private Date dtVencimento;
     private String nrFechamentoapontamento;

    public Contareceber() {
    }

	
    public Contareceber(int cdConta, Cliente cliente, Formapagto formapagto, String nrTitulo, boolean stAtivo, Date dtEmissao, boolean stBaixado, BigDecimal vlTitulo, Date dtVencimento) {
        this.cdConta = cdConta;
        this.cliente = cliente;
        this.formapagto = formapagto;
        this.nrTitulo = nrTitulo;
        this.stAtivo = stAtivo;
        this.dtEmissao = dtEmissao;
        this.stBaixado = stBaixado;
        this.vlTitulo = vlTitulo;
        this.dtVencimento = dtVencimento;
    }
    public Contareceber(int cdConta, Cliente cliente, Formapagto formapagto, String nrTitulo, boolean stAtivo, BigDecimal vlDesconto, Date dtEmissao, boolean stBaixado, BigDecimal vlTitulo, BigDecimal vlAcrescimo, Date dtVencimento, String nrFechamentoapontamento) {
       this.cdConta = cdConta;
       this.cliente = cliente;
       this.formapagto = formapagto;
       this.nrTitulo = nrTitulo;
       this.stAtivo = stAtivo;
       this.vlDesconto = vlDesconto;
       this.dtEmissao = dtEmissao;
       this.stBaixado = stBaixado;
       this.vlTitulo = vlTitulo;
       this.vlAcrescimo = vlAcrescimo;
       this.dtVencimento = dtVencimento;
       this.nrFechamentoapontamento = nrFechamentoapontamento;
    }
   
     @Id 

    
    @Column(name="cd_conta", nullable=false)
    public int getCdConta() {
        return this.cdConta;
    }
    
    public void setCdConta(int cdConta) {
        this.cdConta = cdConta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_formapagto", nullable=false)
    public Formapagto getFormapagto() {
        return this.formapagto;
    }
    
    public void setFormapagto(Formapagto formapagto) {
        this.formapagto = formapagto;
    }

    
    @Column(name="nr_titulo", nullable=false, length=9)
    public String getNrTitulo() {
        return this.nrTitulo;
    }
    
    public void setNrTitulo(String nrTitulo) {
        this.nrTitulo = nrTitulo;
    }

    
    @Column(name="st_ativo", nullable=false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }
    
    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

    
    @Column(name="vl_desconto", precision=15, scale=4)
    public BigDecimal getVlDesconto() {
        return this.vlDesconto;
    }
    
    public void setVlDesconto(BigDecimal vlDesconto) {
        this.vlDesconto = vlDesconto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_emissao", nullable=false, length=29)
    public Date getDtEmissao() {
        return this.dtEmissao;
    }
    
    public void setDtEmissao(Date dtEmissao) {
        this.dtEmissao = dtEmissao;
    }

    
    @Column(name="st_baixado", nullable=false)
    public boolean isStBaixado() {
        return this.stBaixado;
    }
    
    public void setStBaixado(boolean stBaixado) {
        this.stBaixado = stBaixado;
    }

    
    @Column(name="vl_titulo", nullable=false, precision=15, scale=4)
    public BigDecimal getVlTitulo() {
        return this.vlTitulo;
    }
    
    public void setVlTitulo(BigDecimal vlTitulo) {
        this.vlTitulo = vlTitulo;
    }

    
    @Column(name="vl_acrescimo", precision=15, scale=4)
    public BigDecimal getVlAcrescimo() {
        return this.vlAcrescimo;
    }
    
    public void setVlAcrescimo(BigDecimal vlAcrescimo) {
        this.vlAcrescimo = vlAcrescimo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dt_vencimento", nullable=false, length=13)
    public Date getDtVencimento() {
        return this.dtVencimento;
    }
    
    public void setDtVencimento(Date dtVencimento) {
        this.dtVencimento = dtVencimento;
    }

    
    @Column(name="nr_fechamentoapontamento", length=9)
    public String getNrFechamentoapontamento() {
        return this.nrFechamentoapontamento;
    }
    
    public void setNrFechamentoapontamento(String nrFechamentoapontamento) {
        this.nrFechamentoapontamento = nrFechamentoapontamento;
    }




}


