package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Contareceber generated by hbm2java
 */
@Entity
@Table(name = "contareceber",
        schema = "public"
)
public class Contareceber implements java.io.Serializable {

    private int cdContareceber;
    @NotNull
    private Cliente cliente;
    @NotNull
    private Formapagto formapagto;
    @NotBlank
    private String nrTitulo;
    @NotNull
    private Date dtEmissao;
    private boolean stBaixado;
    @Min((long) 0.01)
    private BigDecimal vlTitulo;
    @NotNull
    private Date dtVencimento;
    private int nrFechamentoapontamento;

    public Contareceber() {
    }

    public Contareceber(int cdContareceber, Cliente cliente, Formapagto formapagto, String nrTitulo, Date dtEmissao, boolean stBaixado, BigDecimal vlTitulo, Date dtVencimento) {
        this.cdContareceber = cdContareceber;
        this.cliente = cliente;
        this.formapagto = formapagto;
        this.nrTitulo = nrTitulo;
        this.dtEmissao = dtEmissao;
        this.stBaixado = stBaixado;
        this.vlTitulo = vlTitulo;
        this.dtVencimento = dtVencimento;
    }

    public Contareceber(int cdContareceber, Cliente cliente, Formapagto formapagto, String nrTitulo, Date dtEmissao, boolean stBaixado, BigDecimal vlTitulo, Date dtVencimento, int nrFechamentoapontamento) {
        this.cdContareceber = cdContareceber;
        this.cliente = cliente;
        this.formapagto = formapagto;
        this.nrTitulo = nrTitulo;
        this.dtEmissao = dtEmissao;
        this.stBaixado = stBaixado;
        this.vlTitulo = vlTitulo;
        this.dtVencimento = dtVencimento;
        this.nrFechamentoapontamento = nrFechamentoapontamento;
    }
    

    @Id

    @Column(name = "cd_contareceber", nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public int getCdContareceber() {
        return this.cdContareceber;
    }

    public void setCdContareceber(int cdContareceber) {
        this.cdContareceber = cdContareceber;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @Fetch(FetchMode.JOIN)
    @JoinColumn(name = "cd_cliente", nullable = false)
    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @Fetch(FetchMode.JOIN)
    @JoinColumn(name = "cd_formapagto", nullable = false)
    public Formapagto getFormapagto() {
        return this.formapagto;
    }

    public void setFormapagto(Formapagto formapagto) {
        this.formapagto = formapagto;
    }

    @Column(name = "nr_titulo", nullable = false, length = 9)
    public String getNrTitulo() {
        return this.nrTitulo;
    }

    public void setNrTitulo(String nrTitulo) {
        this.nrTitulo = nrTitulo;
    }



    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dt_emissao", nullable = false, length = 29)
    public Date getDtEmissao() {
        return this.dtEmissao;
    }

    public void setDtEmissao(Date dtEmissao) {
        this.dtEmissao = dtEmissao;
    }

    @Column(name = "st_baixado", nullable = false)
    public boolean isStBaixado() {
        return this.stBaixado;
    }

    public void setStBaixado(boolean stBaixado) {
        this.stBaixado = stBaixado;
    }

    @Column(name = "vl_titulo", nullable = false, precision = 15, scale = 4)
    public BigDecimal getVlTitulo() {
        return this.vlTitulo;
    }

    public void setVlTitulo(BigDecimal vlTitulo) {
        this.vlTitulo = vlTitulo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dt_vencimento", nullable = false, length = 13)
    public Date getDtVencimento() {
        return this.dtVencimento;
    }

    public void setDtVencimento(Date dtVencimento) {
        this.dtVencimento = dtVencimento;
    }

    @Column(name = "nr_fechamentoapontamento")
    public int getNrFechamentoapontamento() {
        return this.nrFechamentoapontamento;
    }

    public void setNrFechamentoapontamento(int nrFechamentoapontamento) {
        this.nrFechamentoapontamento = nrFechamentoapontamento;
    }

}
