package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipamento generated by hbm2java
 */
@Entity
@Table(name="equipamento"
    ,schema="public"
)
public class Equipamento  implements java.io.Serializable {


     private int cdEquipamento;
     private float contInicial;
     private String nrSerie;
     private float contAtual;
     private boolean stAtivo;
     private Set<Unidadeconsumidora> unidadeconsumidoras = new HashSet<Unidadeconsumidora>(0);
     private Set<Apontamento> apontamentos = new HashSet<Apontamento>(0);

    public Equipamento() {
    }

	
    public Equipamento(int cdEquipamento, float contInicial, String nrSerie, float contAtual, boolean stAtivo) {
        this.cdEquipamento = cdEquipamento;
        this.contInicial = contInicial;
        this.nrSerie = nrSerie;
        this.contAtual = contAtual;
        this.stAtivo = stAtivo;
    }
    public Equipamento(int cdEquipamento, float contInicial, String nrSerie, float contAtual, boolean stAtivo, Set<Unidadeconsumidora> unidadeconsumidoras, Set<Apontamento> apontamentos) {
       this.cdEquipamento = cdEquipamento;
       this.contInicial = contInicial;
       this.nrSerie = nrSerie;
       this.contAtual = contAtual;
       this.stAtivo = stAtivo;
       this.unidadeconsumidoras = unidadeconsumidoras;
       this.apontamentos = apontamentos;
    }
   
     @Id 

    
    @Column(name="cd_equipamento", nullable=false)
    public int getCdEquipamento() {
        return this.cdEquipamento;
    }
    
    public void setCdEquipamento(int cdEquipamento) {
        this.cdEquipamento = cdEquipamento;
    }

    
    @Column(name="cont_inicial", nullable=false, precision=8, scale=8)
    public float getContInicial() {
        return this.contInicial;
    }
    
    public void setContInicial(float contInicial) {
        this.contInicial = contInicial;
    }

    
    @Column(name="nr_serie", nullable=false, length=60)
    public String getNrSerie() {
        return this.nrSerie;
    }
    
    public void setNrSerie(String nrSerie) {
        this.nrSerie = nrSerie;
    }

    
    @Column(name="cont_atual", nullable=false, precision=8, scale=8)
    public float getContAtual() {
        return this.contAtual;
    }
    
    public void setContAtual(float contAtual) {
        this.contAtual = contAtual;
    }

    
    @Column(name="st_ativo", nullable=false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }
    
    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipamento")
    public Set<Unidadeconsumidora> getUnidadeconsumidoras() {
        return this.unidadeconsumidoras;
    }
    
    public void setUnidadeconsumidoras(Set<Unidadeconsumidora> unidadeconsumidoras) {
        this.unidadeconsumidoras = unidadeconsumidoras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipamento")
    public Set<Apontamento> getApontamentos() {
        return this.apontamentos;
    }
    
    public void setApontamentos(Set<Apontamento> apontamentos) {
        this.apontamentos = apontamentos;
    }




}


