package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.Valid;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.validator.constraints.Length;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado",
         schema = "public"
)
public class Estado implements java.io.Serializable {

    @NotBlank(message = "É necessário informar o Código do Estado")
    @Length(max = 20)
    private String cdEstado;
    
      
    private Pais pais;
    
    @NotBlank(message = "É necessário informar uma Sigla")
    @Length(max = 5)
    private String sgEstado;
    
    @NotBlank(message = "É necessário informar uma Descrição")
    @Length(max = 100)
    private String dsEstado;
    private boolean stAtivo;
    private Set<Municipio> municipios = new HashSet<>();

    public Estado() {
    }

    public Estado(String cdEstado, Pais pais, String sgEstado, String dsEstado, boolean stAtivo) {
        this.cdEstado = cdEstado;
        this.pais = pais;
        this.sgEstado = sgEstado;
        this.dsEstado = dsEstado;
        this.stAtivo = stAtivo;
    }

    public Estado(String cdEstado, Pais pais, String sgEstado, String dsEstado, boolean stAtivo, Set<Municipio> municipios) {
        this.cdEstado = cdEstado;
        this.pais = pais;
        this.sgEstado = sgEstado;
        this.dsEstado = dsEstado;
        this.stAtivo = stAtivo;
        this.municipios = municipios;
    }

    @Id

    @Column(name = "cd_estado", nullable = false, length = 20)
    public String getCdEstado() {
        return this.cdEstado;
    }

    public void setCdEstado(String cdEstado) {
        this.cdEstado = cdEstado;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cd_pais", nullable = false)
    @Fetch(FetchMode.JOIN)
    public Pais getPais() {
        return this.pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }

    @Column(name = "sg_estado", nullable = false, length = 5)
    public String getSgEstado() {
        return this.sgEstado;
    }

    public void setSgEstado(String sgEstado) {
        this.sgEstado = sgEstado;
    }

    @Column(name = "ds_estado", nullable = false, length = 100)
    public String getDsEstado() {
        return this.dsEstado;
    }

    public void setDsEstado(String dsEstado) {
        this.dsEstado = dsEstado;
    }

    @Column(name = "st_ativo", nullable = false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }

    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }

    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }

    @Override
    public String toString() {
        return "Estado{" + "cdEstado=" + cdEstado + ", pais=" + pais + ", sgEstado=" + sgEstado + ", dsEstado=" + dsEstado + ", stAtivo=" + stAtivo + ", municipios=" + municipios + '}';
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + Objects.hashCode(this.cdEstado);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Estado other = (Estado) obj;
        if (!Objects.equals(this.cdEstado, other.cdEstado)) {
            return false;
        }
        return true;
    }

}
