package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fechamentoapontamento generated by hbm2java
 */
@Entity
@Table(name="fechamentoapontamento"
    ,schema="public"
)
public class Fechamentoapontamento  implements java.io.Serializable {


     private String cdFechamento;
     private Apontamento apontamento;
     private Competencia competencia;
     private Contrato contrato;
     private Tabpreco tabpreco;
     private boolean stAtivo;
     private float vlFechamento;
     private Date dtInclusao;

    public Fechamentoapontamento() {
    }

    public Fechamentoapontamento(String cdFechamento, Apontamento apontamento, Competencia competencia, Contrato contrato, Tabpreco tabpreco, boolean stAtivo, float vlFechamento, Date dtInclusao) {
       this.cdFechamento = cdFechamento;
       this.apontamento = apontamento;
       this.competencia = competencia;
       this.contrato = contrato;
       this.tabpreco = tabpreco;
       this.stAtivo = stAtivo;
       this.vlFechamento = vlFechamento;
       this.dtInclusao = dtInclusao;
    }
   
     @Id 

    
    @Column(name="cd_fechamento", nullable=false, length=9)
    public String getCdFechamento() {
        return this.cdFechamento;
    }
    
    public void setCdFechamento(String cdFechamento) {
        this.cdFechamento = cdFechamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_apontamento", nullable=false)
    public Apontamento getApontamento() {
        return this.apontamento;
    }
    
    public void setApontamento(Apontamento apontamento) {
        this.apontamento = apontamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_competencia", nullable=false)
    public Competencia getCompetencia() {
        return this.competencia;
    }
    
    public void setCompetencia(Competencia competencia) {
        this.competencia = competencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nr_contrato", nullable=false)
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_tabpreco", nullable=false)
    public Tabpreco getTabpreco() {
        return this.tabpreco;
    }
    
    public void setTabpreco(Tabpreco tabpreco) {
        this.tabpreco = tabpreco;
    }

    
    @Column(name="st_ativo", nullable=false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }
    
    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

    
    @Column(name="vl_fechamento", nullable=false, precision=8, scale=8)
    public float getVlFechamento() {
        return this.vlFechamento;
    }
    
    public void setVlFechamento(float vlFechamento) {
        this.vlFechamento = vlFechamento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_inclusao", nullable=false, length=29)
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }




}


