package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formapagto generated by hbm2java
 */
@Entity
@Table(name="formapagto"
    ,schema="public"
)
public class Formapagto  implements java.io.Serializable {


     private String cdFormapagto;
     private String dsFormapagto;
     private boolean stAtivo;
     private Set<Contareceber> contarecebers = new HashSet<Contareceber>(0);

    public Formapagto() {
    }

	
    public Formapagto(String cdFormapagto, String dsFormapagto, boolean stAtivo) {
        this.cdFormapagto = cdFormapagto;
        this.dsFormapagto = dsFormapagto;
        this.stAtivo = stAtivo;
    }
    public Formapagto(String cdFormapagto, String dsFormapagto, boolean stAtivo, Set<Contareceber> contarecebers) {
       this.cdFormapagto = cdFormapagto;
       this.dsFormapagto = dsFormapagto;
       this.stAtivo = stAtivo;
       this.contarecebers = contarecebers;
    }
   
     @Id 

    
    @Column(name="cd_formapagto", nullable=false)
    public String getCdFormapagto() {
        return this.cdFormapagto;
    }
    
    public void setCdFormapagto(String cdFormapagto) {
        this.cdFormapagto = cdFormapagto;
    }

    
    @Column(name="ds_formapagto", nullable=false, length=100)
    public String getDsFormapagto() {
        return this.dsFormapagto;
    }
    
    public void setDsFormapagto(String dsFormapagto) {
        this.dsFormapagto = dsFormapagto;
    }

    
    @Column(name="st_ativo", nullable=false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }
    
    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formapagto")
    public Set<Contareceber> getContarecebers() {
        return this.contarecebers;
    }
    
    public void setContarecebers(Set<Contareceber> contarecebers) {
        this.contarecebers = contarecebers;
    }




}


