package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.util.HashSet;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.web.multipart.MultipartFile;

/**
 * Fotoapontamento generated by hbm2java
 */
@Entity
@Table(name = "fotoapontamento",
        schema = "public"
)
public class Fotoapontamento implements java.io.Serializable {

    private int cdFoto;
    private byte[] ftApontamento;
    private MultipartFile file;
    private Set<Apontamento> apontamentos = new HashSet<>(0);

    public Fotoapontamento() {
    }

    public Fotoapontamento(int cdFoto, byte[] ftApontamento) {
        this.cdFoto = cdFoto;
        this.ftApontamento = ftApontamento;
        file = new MockMultipartFile("img_" + cdFoto, ftApontamento);
    }

    public Fotoapontamento(int cdFoto, byte[] ftApontamento, Set<Apontamento> apontamentos) {
        this.cdFoto = cdFoto;
        this.ftApontamento = ftApontamento;
        this.apontamentos = apontamentos;
        file = new MockMultipartFile("img_" + cdFoto, ftApontamento);
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)

    @Column(name = "cd_foto", nullable = false)
    public int getCdFoto() {
        return this.cdFoto;
    }

    @Transient
    public MultipartFile getFile() {
        return file;
    }

    public void setFile(MultipartFile file) {
        this.file = file;
    }

    public void setCdFoto(int cdFoto) {
        this.cdFoto = cdFoto;
    }

    @Column(name = "ft_apontamento", nullable = false)
    public byte[] getFtApontamento() {
        return this.ftApontamento;
    }

    public void setFtApontamento(byte[] ftApontamento) {
        this.ftApontamento = ftApontamento;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fotoapontamento")
    public Set<Apontamento> getApontamentos() {
        return this.apontamentos;
    }

    public void setApontamentos(Set<Apontamento> apontamentos) {
        this.apontamentos = apontamentos;
    }

}
