package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Frequenciacoleta generated by hbm2java
 */
@Entity
@Table(name="frequenciacoleta"
    ,schema="public"
)
public class Frequenciacoleta  implements java.io.Serializable {


     private int cdFrequenciacoleta;
     private String dsFrequenciacoleta;
     private int qtDias;
     private boolean stAtivo;
     private Set<Contrato> contratos = new HashSet<Contrato>(0);

    public Frequenciacoleta() {
    }

	
    public Frequenciacoleta(int cdFrequenciacoleta, String dsFrequenciacoleta, int qtDias, boolean stAtivo) {
        this.cdFrequenciacoleta = cdFrequenciacoleta;
        this.dsFrequenciacoleta = dsFrequenciacoleta;
        this.qtDias = qtDias;
        this.stAtivo = stAtivo;
    }
    public Frequenciacoleta(int cdFrequenciacoleta, String dsFrequenciacoleta, int qtDias, boolean stAtivo, Set<Contrato> contratos) {
       this.cdFrequenciacoleta = cdFrequenciacoleta;
       this.dsFrequenciacoleta = dsFrequenciacoleta;
       this.qtDias = qtDias;
       this.stAtivo = stAtivo;
       this.contratos = contratos;
    }
   
     @Id 

    
    @Column(name="cd_frequenciacoleta", nullable=false)
    public int getCdFrequenciacoleta() {
        return this.cdFrequenciacoleta;
    }
    
    public void setCdFrequenciacoleta(int cdFrequenciacoleta) {
        this.cdFrequenciacoleta = cdFrequenciacoleta;
    }

    
    @Column(name="ds_frequenciacoleta", nullable=false, length=100)
    public String getDsFrequenciacoleta() {
        return this.dsFrequenciacoleta;
    }
    
    public void setDsFrequenciacoleta(String dsFrequenciacoleta) {
        this.dsFrequenciacoleta = dsFrequenciacoleta;
    }

    
    @Column(name="qt_dias", nullable=false)
    public int getQtDias() {
        return this.qtDias;
    }
    
    public void setQtDias(int qtDias) {
        this.qtDias = qtDias;
    }

    
    @Column(name="st_ativo", nullable=false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }
    
    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="frequenciacoleta")
    public Set<Contrato> getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set<Contrato> contratos) {
        this.contratos = contratos;
    }




}


