package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 14/11/2018 12:26:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemfechamentoId generated by hbm2java
 */
@Embeddable
public class ItemfechamentoId  implements java.io.Serializable {


     private int cdFechamento;
     private int cdApontamento;

    public ItemfechamentoId() {
    }

    public ItemfechamentoId(int cdFechamento, int cdApontamento) {
       this.cdFechamento = cdFechamento;
       this.cdApontamento = cdApontamento;
    }
   


    @Column(name="cd_fechamento", nullable=false)
    public int getCdFechamento() {
        return this.cdFechamento;
    }
    
    public void setCdFechamento(int cdFechamento) {
        this.cdFechamento = cdFechamento;
    }


    @Column(name="cd_apontamento", nullable=false)
    public int getCdApontamento() {
        return this.cdApontamento;
    }
    
    public void setCdApontamento(int cdApontamento) {
        this.cdApontamento = cdApontamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItemfechamentoId) ) return false;
		 ItemfechamentoId castOther = ( ItemfechamentoId ) other; 
         
		 return (this.getCdFechamento()==castOther.getCdFechamento())
 && (this.getCdApontamento()==castOther.getCdApontamento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCdFechamento();
         result = 37 * result + this.getCdApontamento();
         return result;
   }   


}


