package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Itemcondicaopagto generated by hbm2java
 */
@Entity
@Table(name="itemcondicaopagto"
    ,schema="public"
)
public class Itemcondicaopagto  implements java.io.Serializable {


     private ItemcondicaopagtoId id;
     private Condicaopagto condicaopagto;
     private int qtDias;
     private float pcQuota;

    public Itemcondicaopagto() {
    }

    public Itemcondicaopagto(ItemcondicaopagtoId id, Condicaopagto condicaopagto, int qtDias, float pcQuota) {
       this.id = id;
       this.condicaopagto = condicaopagto;
       this.qtDias = qtDias;
       this.pcQuota = pcQuota;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cdCondicaopagto", column=@Column(name="cd_condicaopagto", nullable=false, length=3) ), 
        @AttributeOverride(name="nrSequencia", column=@Column(name="nr_sequencia", nullable=false) ) } )
    public ItemcondicaopagtoId getId() {
        return this.id;
    }
    
    public void setId(ItemcondicaopagtoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_condicaopagto", nullable=false, insertable=false, updatable=false)
    @Fetch(FetchMode.JOIN)
    public Condicaopagto getCondicaopagto() {
        return this.condicaopagto;
    }
    
    public void setCondicaopagto(Condicaopagto condicaopagto) {
        this.condicaopagto = condicaopagto;
    }

    
    @Column(name="qt_dias", nullable=false)
    public int getQtDias() {
        return this.qtDias;
    }
    
    public void setQtDias(int qtDias) {
        this.qtDias = qtDias;
    }

    
    @Column(name="pc_quota", nullable=false, precision=8, scale=8)
    public float getPcQuota() {
        return this.pcQuota;
    }
    
    public void setPcQuota(float pcQuota) {
        this.pcQuota = pcQuota;
    }




}


