package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name="municipio"
    ,schema="public"
)
public class Municipio  implements java.io.Serializable {


     @NotBlank(message = "{message.municipio.dsMunicipio}")
     @Size(max = 20)
     private String cdMunicipio;
     
     private Estado estado;
     @NotBlank(message = "{message.municipio.dsMunicipio}")
     @Size(max = 100)
     private String dsMunicipio;
     private boolean stAtivo;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);

    public Municipio() {
    }

	
    public Municipio(String cdMunicipio, Estado estado, String dsMunicipio, boolean stAtivo) {
        this.cdMunicipio = cdMunicipio;
        this.estado = estado;
        this.dsMunicipio = dsMunicipio;
        this.stAtivo = stAtivo;
    }
    public Municipio(String cdMunicipio, Estado estado, String dsMunicipio, boolean stAtivo, Set<Endereco> enderecos) {
       this.cdMunicipio = cdMunicipio;
       this.estado = estado;
       this.dsMunicipio = dsMunicipio;
       this.stAtivo = stAtivo;
       this.enderecos = enderecos;
    }
   
     @Id 

    
    @Column(name="cd_municipio", nullable=false, length=20)
    public String getCdMunicipio() {
        return this.cdMunicipio;
    }
    
    public void setCdMunicipio(String cdMunicipio) {
        this.cdMunicipio = cdMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
@Fetch(FetchMode.JOIN)
    @JoinColumn(name="cd_estado", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="ds_municipio", nullable=false, length=100)
    public String getDsMunicipio() {
        return this.dsMunicipio;
    }
    
    public void setDsMunicipio(String dsMunicipio) {
        this.dsMunicipio = dsMunicipio;
    }

    
    @Column(name="st_ativo", nullable=false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }
    
    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="municipio")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


