package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name="permissao"
    ,schema="public"
)
public class Permissao  implements java.io.Serializable {


     private int cdPermissao;
     @NotBlank
     private String nmRotina;
     private Set<Permissaotipousuario> permissaotipousuarios = new HashSet<>(0);

    public Permissao() {
    }

	
    public Permissao(int cdPermissao, String nmRotina) {
        this.cdPermissao = cdPermissao;
        this.nmRotina = nmRotina;
    }
    public Permissao(int cdPermissao, String nmRotina, Set<Permissaotipousuario> permissaotipousuarios) {
       this.cdPermissao = cdPermissao;
       this.nmRotina = nmRotina;
       this.permissaotipousuarios = permissaotipousuarios;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="cd_permissao", nullable=false)
    public int getCdPermissao() {
        return this.cdPermissao;
    }
    
    public void setCdPermissao(int cdPermissao) {
        this.cdPermissao = cdPermissao;
    }

    
    @Column(name="nm_rotina", nullable=false, length=100)
    public String getNmRotina() {
        return this.nmRotina;
    }
    
    public void setNmRotina(String nmRotina) {
        this.nmRotina = nmRotina;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="permissao")
    public Set<Permissaotipousuario> getPermissaotipousuarios() {
        return this.permissaotipousuarios;
    }
    
    public void setPermissaotipousuarios(Set<Permissaotipousuario> permissaotipousuarios) {
        this.permissaotipousuarios = permissaotipousuarios;
    }




}


