package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissaotipousuarioId generated by hbm2java
 */
@Embeddable
public class PermissaotipousuarioId  implements java.io.Serializable {


     private int cdPermissao;
     private String cdTipousuario;

    public PermissaotipousuarioId() {
    }

    public PermissaotipousuarioId(int cdPermissao, String cdTipousuario) {
       this.cdPermissao = cdPermissao;
       this.cdTipousuario = cdTipousuario;
    }
   


    @Column(name="cd_permissao", nullable=false)
    public int getCdPermissao() {
        return this.cdPermissao;
    }
    
    public void setCdPermissao(int cdPermissao) {
        this.cdPermissao = cdPermissao;
    }


    @Column(name="cd_tipousuario", nullable=false, length=20)
    public String getCdTipousuario() {
        return this.cdTipousuario;
    }
    
    public void setCdTipousuario(String cdTipousuario) {
        this.cdTipousuario = cdTipousuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermissaotipousuarioId) ) return false;
		 PermissaotipousuarioId castOther = ( PermissaotipousuarioId ) other; 
         
		 return (this.getCdPermissao()==castOther.getCdPermissao())
 && ( (this.getCdTipousuario()==castOther.getCdTipousuario()) || ( this.getCdTipousuario()!=null && castOther.getCdTipousuario()!=null && this.getCdTipousuario().equals(castOther.getCdTipousuario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCdPermissao();
         result = 37 * result + ( getCdTipousuario() == null ? 0 : this.getCdTipousuario().hashCode() );
         return result;
   }   


}


