package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Permissaotipousuario generated by hbm2java
 */
@Entity
@Table(name = "permissaotipousuario",
         schema = "public"
)
public class Permissaotipousuario implements java.io.Serializable, Comparable<Permissaotipousuario> {

    private int cdPermissaotipousuario;
    private Permissao permissao;
    private Tipousuario tipousuario;
    private Date dtInclusao;
    private Date dtUltimaatualizacao;
    private boolean stMarcado = true;
            
    public Permissaotipousuario() {
    }

    @Override
    public int compareTo(Permissaotipousuario o) {
        if (this.permissao.getCdPermissao() < o.getPermissao().getCdPermissao()){
            return -1;
        }
        if (this.permissao.getCdPermissao() > o.getPermissao().getCdPermissao()){
            return 1;
        }
        return 0;
    }

    public Permissaotipousuario(int cdPermissaotipousuario, Permissao permissao, Tipousuario tipousuario, Date dtInclusao, Date dtUltimaatualizacao) {
        this.cdPermissaotipousuario = cdPermissaotipousuario;
        this.permissao = permissao;
        this.tipousuario = tipousuario;
        this.dtInclusao = dtInclusao;
        this.dtUltimaatualizacao = dtUltimaatualizacao;
    }

    public Permissaotipousuario(int cdPermissaotipousuario, Permissao permissao, Tipousuario tipousuario, Date dtInclusao, Date dtUltimaatualizacao, boolean stMarcado) {
        this.cdPermissaotipousuario = cdPermissaotipousuario;
        this.permissao = permissao;
        this.tipousuario = tipousuario;
        this.dtInclusao = dtInclusao;
        this.dtUltimaatualizacao = dtUltimaatualizacao;
        this.stMarcado = stMarcado;
    }

    
    @Id

    @Column(name = "cd_permissaotipousuario", unique = true, nullable = false)
    public int getCdPermissaotipousuario() {
        return this.cdPermissaotipousuario;
    }

    public void setCdPermissaotipousuario(int cdPermissaotipousuario) {
        this.cdPermissaotipousuario = cdPermissaotipousuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @Fetch(FetchMode.JOIN)
    @JoinColumn(name = "cd_permissao", nullable = false)
    public Permissao getPermissao() {
        return this.permissao;
    }
    @Transient
    public boolean isStMarcado() {
        return stMarcado;
    }

    public void setStMarcado(boolean stMarcado) {
        this.stMarcado = stMarcado;
    }

    
    public void setPermissao(Permissao permissao) {
        this.permissao = permissao;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @Fetch(FetchMode.JOIN)
    @JoinColumn(name = "cd_tipousuario", nullable = false)
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }

    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dt_inclusao", nullable = false, length = 29)
    public Date getDtInclusao() {
        return this.dtInclusao;
    }

    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dt_ultimaatualizacao", nullable = false, length = 29)
    public Date getDtUltimaatualizacao() {
        return this.dtUltimaatualizacao;
    }

    public void setDtUltimaatualizacao(Date dtUltimaatualizacao) {
        this.dtUltimaatualizacao = dtUltimaatualizacao;
    }

}
