package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permissaotipousuario generated by hbm2java
 */
@Entity
@Table(name="permissaotipousuario"
    ,schema="public"
)
public class Permissaotipousuario  implements java.io.Serializable {


     private PermissaotipousuarioId id;
     private Permissao permissao;
     private Tipousuario tipousuario;
     private Date dtInclusao;
     private Date dtUltimaatualizacao;

    public Permissaotipousuario() {
    }

    public Permissaotipousuario(PermissaotipousuarioId id, Permissao permissao, Tipousuario tipousuario, Date dtInclusao, Date dtUltimaatualizacao) {
       this.id = id;
       this.permissao = permissao;
       this.tipousuario = tipousuario;
       this.dtInclusao = dtInclusao;
       this.dtUltimaatualizacao = dtUltimaatualizacao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cdPermissao", column=@Column(name="cd_permissao", nullable=false) ), 
        @AttributeOverride(name="cdTipousuario", column=@Column(name="cd_tipousuario", nullable=false, length=20) ) } )
    public PermissaotipousuarioId getId() {
        return this.id;
    }
    
    public void setId(PermissaotipousuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_permissao", nullable=false, insertable=false, updatable=false)
    public Permissao getPermissao() {
        return this.permissao;
    }
    
    public void setPermissao(Permissao permissao) {
        this.permissao = permissao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cd_tipousuario", nullable=false, insertable=false, updatable=false)
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_inclusao", nullable=false, length=29)
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_ultimaatualizacao", nullable=false, length=29)
    public Date getDtUltimaatualizacao() {
        return this.dtUltimaatualizacao;
    }
    
    public void setDtUltimaatualizacao(Date dtUltimaatualizacao) {
        this.dtUltimaatualizacao = dtUltimaatualizacao;
    }




}


