package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tabpreco generated by hbm2java
 */
@Entity
@Table(name="tabpreco"
    ,schema="public"
)
public class Tabpreco  implements java.io.Serializable {


     private int cdTabpreco;
     private BigDecimal vlMetrocubico;
     private BigDecimal vlTaxaadm;
     private Date dtVigenciaini;
     private Date dtVigenciafim;
     private boolean stAtivo;
     private Set<Fechamentoapontamento> fechamentoapontamentos = new HashSet<Fechamentoapontamento>(0);

    public Tabpreco() {
    }

	
    public Tabpreco(int cdTabpreco, BigDecimal vlMetrocubico, BigDecimal vlTaxaadm, Date dtVigenciaini, Date dtVigenciafim, boolean stAtivo) {
        this.cdTabpreco = cdTabpreco;
        this.vlMetrocubico = vlMetrocubico;
        this.vlTaxaadm = vlTaxaadm;
        this.dtVigenciaini = dtVigenciaini;
        this.dtVigenciafim = dtVigenciafim;
        this.stAtivo = stAtivo;
    }
    public Tabpreco(int cdTabpreco, BigDecimal vlMetrocubico, BigDecimal vlTaxaadm, Date dtVigenciaini, Date dtVigenciafim, boolean stAtivo, Set<Fechamentoapontamento> fechamentoapontamentos) {
       this.cdTabpreco = cdTabpreco;
       this.vlMetrocubico = vlMetrocubico;
       this.vlTaxaadm = vlTaxaadm;
       this.dtVigenciaini = dtVigenciaini;
       this.dtVigenciafim = dtVigenciafim;
       this.stAtivo = stAtivo;
       this.fechamentoapontamentos = fechamentoapontamentos;
    }
   
     @Id 

    
    @Column(name="cd_tabpreco", nullable=false)
    public int getCdTabpreco() {
        return this.cdTabpreco;
    }
    
    public void setCdTabpreco(int cdTabpreco) {
        this.cdTabpreco = cdTabpreco;
    }

    
    @Column(name="vl_metrocubico", nullable=false, precision=15, scale=4)
    public BigDecimal getVlMetrocubico() {
        return this.vlMetrocubico;
    }
    
    public void setVlMetrocubico(BigDecimal vlMetrocubico) {
        this.vlMetrocubico = vlMetrocubico;
    }

    
    @Column(name="vl_taxaadm", nullable=false, precision=15, scale=4)
    public BigDecimal getVlTaxaadm() {
        return this.vlTaxaadm;
    }
    
    public void setVlTaxaadm(BigDecimal vlTaxaadm) {
        this.vlTaxaadm = vlTaxaadm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dt_vigenciaini", nullable=false, length=13)
    public Date getDtVigenciaini() {
        return this.dtVigenciaini;
    }
    
    public void setDtVigenciaini(Date dtVigenciaini) {
        this.dtVigenciaini = dtVigenciaini;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dt_vigenciafim", nullable=false, length=13)
    public Date getDtVigenciafim() {
        return this.dtVigenciafim;
    }
    
    public void setDtVigenciafim(Date dtVigenciafim) {
        this.dtVigenciafim = dtVigenciafim;
    }

    
    @Column(name="st_ativo", nullable=false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }
    
    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tabpreco")
    public Set<Fechamentoapontamento> getFechamentoapontamentos() {
        return this.fechamentoapontamentos;
    }
    
    public void setFechamentoapontamentos(Set<Fechamentoapontamento> fechamentoapontamentos) {
        this.fechamentoapontamentos = fechamentoapontamentos;
    }




}


