package br.com.brunoszczuk.apontahidrometro.entities;
// Generated 29/08/2018 23:02:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

/**
 * Tipousuario generated by hbm2java
 */
@Entity
@Table(name = "tipousuario",
         schema = "public"
)
public class Tipousuario implements java.io.Serializable {

    @NotBlank(message = "{message.tipousuario.cdtipousuario}")
    @Size(max = 20)
    private String cdTipousuario;
    @NotBlank(message = "{message.tipousuario.dstipousuario}")
    @Size(min = 3, max = 100)
    private String dsTipousuario;
    private boolean stAtivo;
    private Set<Usuario> usuarios = new HashSet<>(0);
    private Set<Permissaotipousuario> permissaotipousuarios = new HashSet<>(0);

    public Tipousuario() {
    }

    public Tipousuario(String cdTipousuario, String dsTipousuario, boolean stAtivo) {
        this.cdTipousuario = cdTipousuario;
        this.dsTipousuario = dsTipousuario;
        this.stAtivo = stAtivo;
    }

    public Tipousuario(String cdTipousuario, String dsTipousuario, boolean stAtivo, Set<Usuario> usuarios, Set<Permissaotipousuario> permissaotipousuarios) {
        this.cdTipousuario = cdTipousuario;
        this.dsTipousuario = dsTipousuario;
        this.stAtivo = stAtivo;
        this.usuarios = usuarios;
        this.permissaotipousuarios = permissaotipousuarios;
    }

    @Id

    @Column(name = "cd_tipousuario", nullable = false, length = 20)
    public String getCdTipousuario() {
        return this.cdTipousuario;
    }

    public void setCdTipousuario(String cdTipousuario) {
        this.cdTipousuario = cdTipousuario;
    }

    @Column(name = "ds_tipousuario", nullable = false, length = 100)
    public String getDsTipousuario() {
        return this.dsTipousuario;
    }

    public void setDsTipousuario(String dsTipousuario) {
        this.dsTipousuario = dsTipousuario;
    }

    @Column(name = "st_ativo", nullable = false)
    public boolean isStAtivo() {
        return this.stAtivo;
    }

    public void setStAtivo(boolean stAtivo) {
        this.stAtivo = stAtivo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipousuario")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipousuario")
    public Set<Permissaotipousuario> getPermissaotipousuarios() {
        return this.permissaotipousuarios;
    }

    public void setPermissaotipousuarios(Set<Permissaotipousuario> permissaotipousuarios) {
        this.permissaotipousuarios = permissaotipousuarios;
    }

}
